### ISSUE TITLE
Bug: menu is truncated by small windows

### ISSUE THREAD

**Issue by simonw** [HeyPuter/puter#16]
Spotted this:

![menu-bug](https://github.com/HeyPuter/puter/assets/9599/9d2b17e5-3573-4231-a31b-dbc368ba8904)

If an application window is too short, any menus opened will be truncated meaning you cannot see the options at the bottom of those menus.

**Comment by jelveh** [comment]
Thank you for reporting this issue. This is caused by the menu UI being rendered in the iframe that hosts the app, which makes for poor UI/UX issues similar to this. What I'm doing right now is building a mechanism through which the menu is rendered by the desktop rather than the app. It'll take some time, but it's coming 🚀

**Comment by KernelDeimos** [comment]
Also applies to the context menu when the app window has a small vertical size. Also, I wonder what we do if the viewports vertical size is small; just clip it or do a

```
| [ Item 1 ]  [ Item 3 ] |
| [ Item 2 ]             |
```

**Comment by jelveh** [comment]
This took a while! 😅
@simonw this issue has been fixed, in fact we have a whole set of APIs for menubar and context menu now! (Please note that the fix is not available on puter.com yet)
