### ISSUE TITLE
Media corrupted (File)

### ISSUE THREAD

**Issue by bobanilic** [HeyPuter/puter#263]
**Issue Description**
I stored simple media file (4mb) which got corrupted. Uploaded 10days+ ago and it worked fine till today. 
**Steps to Reproduce**
Healthy file > Few days > Corrupted file

**Expected & Actual Behavior**
To play simple media file as before(4mb) > Corrupted media file (1kb)
**Addition Information or Screenshots (if applicable)**
Both self-hosted puter and puter.com dont work. Apps from store don't work on "local development" (they work on puter.com)

**Tooling**
- Deployed via Local Development

**Puter version (if accessible)**
Version: v1.2.42-beta-72-g48672fe4 • Server: frankfurt • Deployed: Wed Apr 10 2024 19:27:02 GMT+0200 (Central European Summer Time)

**Comment by KernelDeimos** [comment]
> Both self-hosted puter and puter.com dont work

Can you elaborate on this? Did you encounter two corrupted files - one on each deployment?

**Comment by bobanilic** [comment]
> Can you elaborate on this? Did you encounter two corrupted files - one on each deployment?

I logged in with 1 account I made on puter.com and used it on localhost too, therefore it had the same file. I hoped I could use my own storage on local host but I couldn't (domain:4000)

**Comment by KernelDeimos** [comment]
> and used it on localhost too

Thanks, that makes a lot more sense. You're running a relatively old version of this repo before the self-hosted backend was available, so we would consider that to still be `puter.com` rather than self-hosted. The current self-hosted version doesn't (currently) allow login via `puter.com` and it _does_ store files locally.

As for the corrupted file, please link this PR in an email to `support@puter.com` and we can help you further. I'll leave this issue open until we know what the cause is.
