### ISSUE TITLE
Problems with running Terminal or Phoenix

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#285]
I've been having trouble getting these to run, either on Puter, or with Phoenix's CLI. So far I've identified:

- [ ] Puter platform files are missing - #283 
- [ ] `xterm.css` isn't being copied to `builtin/terminal/xterm.css`
- [ ] `phoenix` dependencies aren't installed, causing `bundle.js:13279 Uncaught ReferenceError: contextlink is not defined` in the browser, and `Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'contextlink' imported from /home/sam/Projects/HeyPuter/puter/packages/phoenix/src/main_cli.js` when running the CLI.

The dependencies issue might be something simple, but `npm install` hasn't helped, either in the `phoenix` dir itself or in the root, and that's about as far as my npm knowledge goes. :sweat_smile:

**Comment by KernelDeimos** [comment]
fixed by 25f8dbf12010eead3cb9ba03a6fa4bb1fdf93502, c72e0cb0e00769334059299610f4d31b376ae620, 4d30753958d6eec27265a3771ebea457042c0f01, 081b093e7ea66a0975e61ffdc642b73225f9c0f0, f3495f30980257c3b27355170528587200834bdd, and 1c2b05d8f663c16142ea677b44eac01230c30b53. That... wasn't as easy as I feel like it should have been.

**Comment by AtkinsSJ** [comment]
Oh boy. I'm glad you got there in the end. 😬
