### ISSUE TITLE
Tiling window managment

### ISSUE THREAD

**Issue by Jak2k** [HeyPuter/puter#29]

**Comment by jelveh** [comment]
@KernelDeimos 's dream is about to come true!

**Comment by vineeth-vk11** [comment]
@jelveh this looks interesting, I want to give this a try.

**Comment by KernelDeimos** [comment]
Some prerequisite issues to this:
- window management needs to be decoupled from everything else
- ensuring single-source-of-truth for state across the board will help greatly
- do we need to move to web components first? We might create more work later if we don't
- good keybind management is absolutely necessary for this

I've used both i3 and xmonad, and I prefer i3's approach so that's what I'd recommend.

One thing that's important to know: this task is a long road. A very rewarding road though, since the changes necessary to make this possible will improve the stability, flexibility, and maintainability of Puter's ui.

**Comment by jelveh** [comment]
this escalated quickly.

**Comment by vineeth-vk11** [comment]
It sure did, let me spend some time understanding what @KernelDeimos has suggested.

**Comment by Jak2k** [comment]
What about auto-tiling with extensive configuration, like hyprland does?

**Comment by KernelDeimos** [comment]
> What about auto-tiling with extensive configuration, like hyprland does?

That definitely changes the nature of this task and makes it a bit simpler. Keybind configuration remains very important for that but the implementation could definitely be more like KDE's tiling feature.

I really prefer the idea of it being a "replacement window manager" since that would make gui a lot more flexible for different use-cases, but this could be a very good intermediate solution.

**Comment by KernelDeimos** [comment]
> Auto-tiling places the window in the half of the currently focused window
I didn't understand this, do you mean the focused window covers half the screen? With auto-tiling you might be describing the same thing I was talking before regarding `i3`; i3 automatically tiles the windows, i.e. rather than having a key combination that "tiles it" everything is always tiled.

**Comment by Jak2k** [comment]
> > Auto-tiling places the window in the half of the currently focused window
> 
> I didn't understand this, do you mean the focused window covers half the screen? With auto-tiling you might be describing the same thing I was talking before regarding `i3`; i3 automatically tiles the windows, i.e. rather than having a key combination that "tiles it" everything is always tiled.

Hyprland let's you choose between dwindle and master layout:

- **Dwindle**: Looks, which window is focused; splits it in half; one half is that window, the other is the new window; when a mouse is placed in a window half, this is where the new window goes
- **Master**: One half of the screen is one window; the other half contains the other windows in a vertical stack
