### ISSUE TITLE
When I use file sharing, after successfully sharing, I cannot find the shared file in the shared files

### ISSUE THREAD

**Issue by mailyxf** [HeyPuter/puter#764]
**Issue Description**
When I use file sharing, after successfully sharing, I cannot find the shared file in the shared files
**Steps to Reproduce**

**Expected & Actual Behavior**

**Addition Information or Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/f26bbad2-4e02-47e8-ab67-b7897eb7eb33)

**Deployment**
- [ ] Production (puter.com)
- [ ✓] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

**Comment by mailyxf** [comment]
I can't work on centos, I work well on mac

**Comment by KernelDeimos** [comment]
That's odd that you're observing an error on CentOS but not MacOS. Most of the testing for this has been done in a Linux environment so I would expect this to happen the other way around if anything. My suspicion is there is something else that's different between the two devices. What happens if you run it in a VM running another distro?

**Comment by mailyxf** [comment]
I found the reason: it was because I used Windows during the first initialization and created a new file, which caused the file path format stored in the database to be "\"
